//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activityunit
    {
        public activityunit()
        {
            this.tags = new HashSet<tag>();
        }
    
        public long id { get; set; }
        public int activity_id { get; set; }
        public int location_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime stime { get; set; }
        public System.DateTime etime { get; set; }
    
        public virtual activity activity { get; set; }
        public virtual location location { get; set; }
        public virtual ICollection<tag> tags { get; set; }
    }
}
