//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity
    {
<<<<<<< .merge_file_a08764
        public int id { get; set; }
        public int user { get; set; }
        public string name { get; set; }
        public Nullable<byte> category { get; set; }
=======
        public activity()
        {
            this.activity_units = new HashSet<activity_units>();
        }
    
        public int id { get; set; }
        public int user { get; set; }
        public string name { get; set; }
        public byte category { get; set; }
    
        public virtual user user1 { get; set; }
        public virtual ICollection<activity_units> activity_units { get; set; }
>>>>>>> .merge_file_a09244
    }
}
