//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class csci4950s15Entities : DbContext
    {
        public csci4950s15Entities()
            : base("name=csci4950s15Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activity> activities { get; set; }
        public virtual DbSet<activityunit> activityunits { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<tags_users> tags_users { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
