//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tag
    {
        public tag()
        {
            this.tags_users = new HashSet<tags_users>();
            this.activities = new HashSet<activity>();
            this.activityunits = new HashSet<activityunit>();
            this.locations = new HashSet<location>();
        }
    
        public byte id { get; set; }
        public string name { get; set; }
        public string default_color { get; set; }
    
        public virtual ICollection<tags_users> tags_users { get; set; }
        public virtual ICollection<activity> activities { get; set; }
        public virtual ICollection<activityunit> activityunits { get; set; }
        public virtual ICollection<location> locations { get; set; }
    }
}
